### ISSUE TITLE
Waves on screen

### ISSUE THREAD

**Issue by Djoulzy** [TheRetroChannel/C128-C64-Shortboard-RF-replacement#1]
Hi, I just finished the build of my pcb ...
Honestly, the image is the best I've seen compared to all other replacement board I've tried.
But there're some kind of waves on the screen like if something was'nt isolated correctly (from PSU or other).
Did you faced this issue before ?
Did I missed something ?

Some details:
- C128DCR
- 1084S
- Standard video cable/output (did not use the new s-video output)

**Comment by TheRetroChannel** [comment]
@Djoulzy Can you take a picture or describe the waves you're seeing? Are they horizontal, vertical, what size?

**Comment by Djoulzy** [comment]
Mark,
Here is some pictures …
We can see some « horizontal » wave that change their freqency during time in some kind of cycle. bigger and slower.

￼￼

**Comment by Djoulzy** [comment]
![IMG_5420](https://github.com/TheRetroChannel/C128-C64-Shortboard-RF-replacement/assets/29226401/8594ea46-771c-400b-8e45-409fc1f9661d)
![IMG_5419](https://github.com/TheRetroChannel/C128-C64-Shortboard-RF-replacement/assets/29226401/1c45a01b-dd3b-4e26-bf0f-a78ac29b47b4)

**Comment by TheRetroChannel** [comment]
Ok yep, it looks like noise from the PSU. You can try adding an electrolytic capacitor between 5V and GND. The easiest place to put it is at the inputs to the RF replacement, with the positive side soldered to the far right pin and negative on the 3rd pin from the right. Something between 47uF and 220uF should be suitable and at least 10V.
![Screenshot_20231231_194242_Chrome](https://github.com/TheRetroChannel/C128-C64-Shortboard-RF-replacement/assets/100115197/9b8bc0e7-120d-45d1-b486-60636af19e0f)

**Comment by Djoulzy** [comment]
Perfect, I'll try this tomorrow (for the new year :)
And I wish you a happy new year !

**Comment by Djoulzy** [comment]
Hey ! I put a 100uF and it works perfectly !
Very good job ...
... and I will see you in your next video !

**Comment by TheRetroChannel** [comment]
Awesome! Thanks for letting me know. Enjoy!
